import ServiceBox from '../components/ServiceBox'
import BookingButton from '../components/BookingButton'
// Icons generated by Google Gemini
import consultation from '../assets/consultation.png';
import studyModels from '../assets/studyModels.png';
import rootCanal from '../assets/rootCanal.png';
import compositeFiling from '../assets/compositeFiling.png';
import gicFiling from '../assets/gicFiling.png';
import dentalExtraction from '../assets/dentalExtraction.png';
import childrenExtraction from '../assets/childrenExtraction.png';
import openDisimpaction from '../assets/openDisimpaction.png';
import closedDisimpaction from '../assets/closedDisimpaction.png';
import fullMouth from '../assets/fullMouth.png';
import oralProphylaxis from '../assets/oralProphylaxis.png';
import bleaching from '../assets/bleaching.png';
import dentures from '../assets/dentures.png';

export default function Services() {
    const services = [
        {
            'icon': consultation,
            'title': 'Consultation',
            'text': 'A comprehensive clinical assessment to evaluate oral health and discuss personalized treatment goals'
        },
        {
            'icon': studyModels,
            'title': 'Study Models',
            'text': 'Accurate physical replicas of your teeth used for precise treatment planning and diagnostic analysis.',
        },
        {
            'icon': compositeFiling,
            'title': 'Composite Filling',
            'text': 'A tooth-coloured resin restoration that seamlessly repairs cavities while maintaining a natural appearance.',
        },
        {
            'icon': gicFiling,
            'title': 'GIC Filling',
            'text': 'A fluoride-releasing material ideal for protecting teeth and restoring cavities in low-pressure areas.',
        },
        {
            'icon': dentalExtraction,
            'title': 'Dental Extraction',
            'text': 'The safe and gentle removal of a damaged or problematic tooth to preserve overall health.',
        },
        {
            'icon': childrenExtraction,
            'title': 'Children Tooth Extraction',
            'text': 'Specialized, compassionate removal of primary teeth to ensure proper spacing and comfort for kids.'
        },
        {
            'icon': rootCanal,
            'title': 'Root Canal',
            'text': 'Expert endodontic treatment to save infected teeth and relieve pain.'
        },
        {
            'icon': openDisimpaction,
            'title': 'Open Disimpaction',
            'text': 'A surgical procedure involving a small incision to access and remove deeply impacted teeth.'
        },
        {
            'icon': closedDisimpaction,
            'title': 'Closed Disimpaction',
            'text': 'The expert removal of an impacted tooth that hasn\'t fully emerged through the gum line.'
        },
        {
            'icon': fullMouth,
            'title': 'Full Mouth Scaling and Polishing',
            'text': 'A deep cleaning treatment that removes hardened plaque and surface stains for a fresh smile.'
        },
        {
            'icon': oralProphylaxis,
            'title': 'Oral Prophylaxis',
            'text': 'Professional cleaning and preventative care designed to stop gum disease before it starts.'
        },
        {
            'icon': bleaching,
            'title': 'Bleaching',
            'text': 'A professional whitening treatment that safely lifts stains to brighten your teeth by several shades.'
        },
        {
            'icon': dentures,
            'title': 'Dentures',
            'text': 'Custom-crafted removable appliances designed to restore the function and look of missing teeth.'
        }
    ]
    return(
        <div id="services" className="pt-4">
            <h1 className="text-center sectionHeadings">Services</h1>
            <p className="text-center text-secondary" style={{ width: "50%", marginLeft: "25%" }}>We offer a comprehensive range of dental services to meet all your oral health needs</p>

            <div className="px-5 d-flex flex-direction-row flex-wrap justify-content-around">
                {services.map((service) => {
                    return <ServiceBox key={service.title} icon={service.icon} title={service.title} text={service.text} />
                })}
            </div>
            <div className="text-center pb-4">
                <BookingButton />
            </div>
        </div>
    )
}