import ServiceBox from '../components/ServiceBox'
import BookingButton from '../components/BookingButton'
// Icons generated by Google Gemini
import consultation from '../assets/consultation.png';
import studyModels from '../assets/studyModels.png';
import rootCanal from '../assets/rootCanal.png';
import compositeFiling from '../assets/compositeFiling.png';
import gicFiling from '../assets/gicFiling.png';
import dentalExtraction from '../assets/dentalExtraction.png';
import childrenExtraction from '../assets/childrenExtraction.png';
import openDisimpaction from '../assets/openDisimpaction.png';
import closedDisimpaction from '../assets/closedDisimpaction.png';
import fullMouth from '../assets/fullMouth.png';
import oralProphylaxis from '../assets/oralProphylaxis.png';
import bleaching from '../assets/bleaching.png';
import dentures from '../assets/dentures.png';

export default function Services() {
    const services = [
        {
            'icon': consultation,
            'title': 'Consultation',
            'text': 'We offer the most comprehensive clinical assessment to evaluate oral health and discuss personalized treatment goals in Nairobi.'
        },
        {
            'icon': studyModels,
            'title': 'Study Models',
            'text': 'Spearmint Dental Clinic is your place to go in Nairobi for accurate physical replicas of your teeth.',
        },
        {
            'icon': compositeFiling,
            'title': 'Composite Filling',
            'text': 'Come to Spearmint Dental Clinic Nairobi for tooth-coloured resin restoration that seamlessly repairs cavities while maintaining a natural appearance.',
        },
        {
            'icon': dentalExtraction,
            'title': 'Dental Extraction',
            'text': 'The safe and gentle removal of a damaged or problematic tooth to preserve overall health.',
        },
        {
            'icon': childrenExtraction,
            'title': 'Children Tooth Extraction',
            'text': 'Want to get your kid\'s primary dental teeth removed in Nairobi? Spearmint Dental Clinic, Nairobi is the place for you.'
        },
        {
            'icon': rootCanal,
            'title': 'Root Canal',
            'text': 'Our expert dentists are here to perform your root canal and releive tooth pain at an affordable cost in Nairobi.'
        },
        {
            'icon': openDisimpaction,
            'title': 'Open Disimpaction',
            'text': 'Get your tooth disimpaction in the Nairobi area at Spearmint Dental Clinic for the best treatment at extremely low prices.'
        },
        {
            'icon': fullMouth,
            'title': 'Full Mouth Scaling and Polishing',
            'text': 'Refresh your smile with a full mouth dental cleaning and polishing with us. Simply book an appointment and get a whole new smile.'
        },
        {
            'icon': oralProphylaxis,
            'title': 'Oral Prophylaxis',
            'text': 'If you are looking for professional dental cleaning and preventative care, come to Spearmint Dental Clinic, Nairobi.'
        },
        {
            'icon': bleaching,
            'title': 'Bleaching',
            'text': 'Get professional teeth whitening treatment at Spearmint Dental Clinic, Nairobi that safely lifts stains to brighten your teeth by several shades.'
        },
        {
            'icon': dentures,
            'title': 'Dentures',
            'text': 'Want custom-crafted removable dentures in Nairobi? Make a booking with us today.'
        }
    ]
    return(
        <div id="services" className="pt-4">
            <h1 className="text-center sectionHeadings">Services</h1>
            <p className="text-center text-secondary" style={{ width: "50%", marginLeft: "25%" }}>At Spearmint Dental Clinic Nairobi, we offer a comprehensive range of dental services at an affordable price in Nairobi near Hurlingham to meet all your oral health needs</p>

            <div className="px-5 d-flex flex-direction-row flex-wrap justify-content-around">
                {services.map((service) => {
                    return <ServiceBox key={service.title} icon={service.icon} title={service.title} text={service.text} />
                })}
            </div>
            <div className="text-center pb-4">
                <BookingButton />
            </div>
        </div>
    )
}