import ServiceBox from '../components/ServiceBox'
import BookingButton from '../components/BookingButton'
// Icons generated by Google Gemini
import generalDentistry from '../assets/generalDentistry.png'
import orthodontics from '../assets/orthodontics.png'
import dentalImplants from '../assets/dentalImplants.png'
import emergency from '../assets/emergency.png'
import teethWhitening from '../assets/teethWhitening.png'
import rootCanal from '../assets/rootCanal.png'


export default function Services() {
    const services = [
        {
            'icon': generalDentistry,
            'title': 'General Dentistry',
            'text': 'Comprehensive oral health care including check-ups, cleanings, and preventive treatments.'
        },
        {
            'icon': teethWhitening,
            'title': 'Teeth Whitening',
            'text': 'Professional whitening treatments to brighten your smile and boost your confidence.',
        },
        {
            'icon': dentalImplants,
            'title': 'Dental Implants',
            'text': 'Permanent tooth replacement solutions that look and function like natural teeth.',
        },
        {
            'icon': orthodontics,
            'title': 'Orthodontics',
            'text': 'Braces and aligners to straighten teeth and improve bite alignment.',
        },
        {
            'icon': rootCanal,
            'title': 'Root Canal',
            'text': 'Expert endodontic treatment to save infected teeth and relieve pain.',
        },
        {
            'icon': teethWhitening,
            'title': 'Cosmetic Services',
            'text': 'Expert cosmetic services, offering custom dental veneers and masking to seamlessly conceal imperfections.'
        },
        {
            'icon': emergency,
            'title': 'Emergency Care',
            'text': 'Immediate dental care for urgent situations and dental emergencies.'
        }
    ]
    return(
        <div id="services" className="pt-4">
            <h1 className="text-center sectionHeadings">Services</h1>
            <p className="text-center text-secondary" style={{ width: "50%", marginLeft: "25%" }}>We offer a comprehensive range of dental services to meet all your oral health needs</p>

            <div className="px-5 d-flex flex-direction-row flex-wrap justify-content-around">
                {services.map((service) => {
                    return <ServiceBox key={service.title} icon={service.icon} title={service.title} text={service.text} />
                })}
            </div>
            <div className="text-center pb-4">
                <BookingButton />
            </div>
        </div>
    )
}