import "@chatscope/chat-ui-kit-styles/dist/default/styles.min.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Header from './components/Header';
import Hero from './pages/Hero';
import Services from './pages/Services';
import Team from './pages/Team';
import BookAppointment from './pages/BookAppointment';
import Footer from './components/Footer';
import Location from './pages/Location';
import { MainContainer, ChatContainer, MessageList, Message, MessageInput, TypingIndicator } from "@chatscope/chat-ui-kit-react";
import { Modal, Button, Form, InputGroup } from 'react-bootstrap';
import { useState } from 'react';
import chatbot from './assets/chatbot.png'
import send from './assets/send.png'
import './styles/styles.css'

export default function App() {
    const [show, setShow] = useState(false);
    const [typing, setTyping] = useState(false);
    
    const handleShow = () => setShow(true);
    const handleClose = () => setShow(false);

    const [messages, setMessages] = useState([
        {
        message: "Hello! How can I help?",
        sender: "bot"
        }
    ]);

    const handleSend = async (text) => {
        const userMessage = {
            message: text,
            sender: "user"
        };

        // Add user message
        setMessages((prev) => [...prev, userMessage]);

        try {
            setTyping(true);
            const response = await fetch("https://botsasa-6acp.onrender.com/chatbot", {
            method: "POST",
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ text: text, apikey: import.meta.env.VITE_CHATBOT_KEY })
            });

            const data = await response.json();

            const botMessage = {
            message: data.response.answer,
            sender: "bot"
            };

            // Add bot response
            setMessages((prev) => [...prev, botMessage]);
            setTyping(false);
        } catch (error) {
            console.error(error);
        }
    };

    return(
        <>
            <Header />
            <Hero />
            <Services />
            <Team />
            <BookAppointment />
            <Footer />
            <Button id="chatbotIcon" onClick={handleShow}>
                <img src={chatbot} alt="Chatbot icon" style={{ width: '90%' }} />
            </Button>
        
            <Modal show={show} onHide={handleClose} id="modal">
                <Modal.Header className='modalHeader' closeButton>
                    <img src={chatbot} alt="Chatbot icon" style={{ width: '40px' }} className="img-fluid" />
                </Modal.Header>
                <Modal.Body id="modalBody" className='d-flex flex-column'>
                    <MainContainer>
                        <ChatContainer>
                        <MessageList typingIndicator={typing ? <TypingIndicator content="Bot is typing..." /> : null} >
                            {messages.map((msg, index) => (
                                <Message
                                    key={index}
                                    model={{
                                        message: msg.message,
                                        sender: msg.sender,
                                        direction: msg.sender === "user" ? "outgoing" : "incoming"
                                    }}
                                    />
                            ))}
                        </MessageList>
                        <MessageInput placeholder="Type message here..." onSend={handleSend} attachButton={false} />
                        </ChatContainer>
                    </MainContainer>
                    <p className="text-danger" style={{ 'fontSize': '12px' }}><small>These responses are generated by an AI model and are prone to error. Please call or WhatsApp +254701-561-597 for major inquiries.</small></p>
                </Modal.Body>
            </Modal>
        </>
    )
}